tugas_akhir/cekin/urls.py
from django.urls import path

from . import views

app_name = 'cekin'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/',views.imgGerbang, name='image_gerbang'),
    path('tambah/',views.tambahImage, name='image_tambah'),
    path('deteksi/',views.deteksiImage, name='image_deteksi'),
    path('simpan/',views.simpanImage, name='image_simpan'),
    path('video/',views.videoGerbangMasuk, name='video_gerbang'),
    path('camera/', views.aturCamera, name='atur_camera'),
    path('set/', views.setImage, name='set_image'),
    path('<int:pk>/lihat/',views.lihatGambar, name='lihat_gambar'),
] 

tugas_akhir/cekin_paraller/urls.py
from django.urls import path

from . import views

app_name = 'cekin_paraller'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/',views.imgGerbang, name='image_gerbang'),
    path('tambah/',views.tambahImage, name='image_tambah'),
    path('deteksi/',views.deteksiImage, name='image_deteksi'),
    path('simpan/',views.simpanImage, name='image_simpan'),
    path('<int:pk>/lihat/',views.lihatGambar, name='lihat_gambar'),
] 

tugas_akhir/cekout/urls.py
from django.urls import path

from . import views

app_name = 'cekout'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/', views.image, name='image'),
    path('harga/', views.aturHarga, name='atur_harga'),
    path('selesai/', views.parkirSelesai, name='selesai'),
] 

tugas_akhir/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('video_ori/', views.videoOri, name='video_ori'),
    path('video_tracking/', views.videoTracking, name='video_tracking'),
    path('camera/', views.aturCamera, name='atur_camera'),
] 

tugas_akhir/mobil/urls.py
from django.urls import path

from . import views

app_name = 'mobil'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create_kendaraan'),
    path('<int:pk>/edit/', views.edit, name='edit_kendaraan'),
    path('<int:pk>/delete/', views.delete, name='delete_kendaraan'),
    path('<int:pk>/lihat/', views.lihatParkir, name='lihat_parkir'),
] 

tugas_akhir/parkir/urls.py
from django.urls import path

from . import views

app_name = 'parkir'
urlpatterns = [
    path('titik/', views.titik, name='titik'),
    path('titik/img/',views.imgTitik, name='image_titik'),
    path('titik/img/ganti/', views.editGambar, name='ganti_gambar'),
    path('titik/create/',views.createPosisi, name='create_posisi'),
    path('titik/<int:pk>/edit/', views.editPosisi, name='edit_posisi'),
    path('titik/<int:pk>/delete/', views.deletePosisi, name='delete_posisi'),
    path('cari_mobil/', views.cari_kendaraan_template, name='cari_mobil'), # template
    path('cari_kendaraan/', views.cari_kendaraan, name='cari_kendaraan'), # cari kendaraan
    path('parkir_kosong/',views.tempat_kosong_template, name='parkir_kosong'), # template
    path('img_tempat_kosong/', views.img_tempat_kosong, name='img_tempat_kosong'), # cari tempat kosong
] 

tugas_akhir/tugas_akhir/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('user_manage.urls')),
    path('home/', include('dashboard.urls')),
    path('gerbang/masuk/', include('cekin.urls')),
    path('gerbang/paraller/masuk/', include('cekin_paraller.urls')),
    path('gerbang/keluar/', include('cekout.urls')),
    path('mobil/', include('mobil.urls')),
    path('parkir/', include('parkir.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

tugas_akhir/dashboard/models.py
from django.db import models

# Create your models here.
class Camera(models.Model):
    FileVideo = 0
    WebCamera = 1
    IpCamera = 3
    Camera_TYPES = (
        (FileVideo, 'File Video'),
        (WebCamera, 'Web Camera'),
        (IpCamera, 'IP camera'),
    )
    ip_camera = models.CharField(max_length=200)
    file_camera = models.CharField(max_length=200, default= "")
    web_camera = models.IntegerField()
    status_active = models.PositiveSmallIntegerField(choices=Camera_TYPES)

tugas_akhir/dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,StreamingHttpResponse,HttpResponseServerError,JsonResponse
from django.views.decorators import gzip
from django.db.models import Prefetch
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required


from mobil.models import Kendaraan
from parkir.models import Posisi
from paket.reza import VideoProses, IpCamera
from .models import Camera
from .formsCamera import CameraForm

import os
import json

# Create your views here.
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# loop frame video
def gen_ori(camera,status):
    mobil = Kendaraan.objects.filter(status_kendaraan=True,status_parkir=False)# kenapa ada ini biar waktu eksekusi sama
    camera.setGambarMobil(mobil)        
    if status == True:
        while True:
            frame ,frame_track = camera.get_frame()
            yield(b'--frame\r\n'
            b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
    else:
        frame = camera.get_frameFail()
        yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def gen_tracking(camera,status):
    titik = Posisi.objects.raw("SELECT parkir_posisi.id, parkir_posisi.nama, parkir_posisi.koordinat, mobil_kendaraan.plat_nomor FROM parkir_posisi LEFT JOIN parkir_parkir ON parkir_posisi.id = parkir_parkir.id_posisi_id LEFT JOIN mobil_kendaraan ON parkir_parkir.id_kendaraan_id = mobil_kendaraan.id")
    mobil = Kendaraan.objects.filter(status_kendaraan=True,status_parkir=False)
    camera.setSize((768,432))
    camera.setGambarMobil(mobil)
    camera.setTitikParkir(titik)
    if status == True:
        while True:
            frame, frame_track = camera.get_frame()
            # frame, frame_track = camera.get_frame_rstp()
            yield(b'--frame\r\n'
            b'Content-Type: image/jpeg\r\n\r\n' + frame_track + b'\r\n\r\n')            
    else:
        frame = camera.get_frameFail()
        yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

# view untuk demo video
@gzip.gzip_page
def videoOri(request):
    global PROJECT_ROOT
    kamera = Camera.objects.get(id=1)# id 1 untuk tempat parkir
    if kamera.status_active == 0:
        vid = VideoProses() 
        cam = vid.setVideo(PROJECT_ROOT+kamera.file_camera)
    elif kamera.status_active == 1:
        vid = VideoProses()
        cam = vid.setVideo(kamera.web_camera)
    else:
        vid = IpCamera()
        cam = vid.setUrl(kamera.ip_camera)
        # cam = vid setUrlRstp(kamera.ip_camera)
    try:
        return StreamingHttpResponse(gen_ori(vid,cam),content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        return HttpResponse(e)

@gzip.gzip_page
def videoTracking(request):
    global PROJECT_ROOT
    kamera = Camera.objects.get(id=1)
    if kamera.status_active == 0:
        vid = VideoProses() 
        cam = vid.setVideo(PROJECT_ROOT+kamera.file_camera)
    elif kamera.status_active == 1:
        vid = VideoProses()
        cam = vid.setVideo(kamera.web_camera)
    else:
        vid = IpCamera()
        # cam = vid.setUrl(kamera.ip_camera)
        cam = vid.setUrlRstp(kamera.ip_camera)
    try:
        return StreamingHttpResponse(gen_tracking(vid,cam),content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        return HttpResponse(e)

@login_required
def index(request):
    kendaraan = Kendaraan.objects.all().count()
    return render(request, 'dashboard/index.html',{'kendaraan':kendaraan})

@login_required
def aturCamera(request):
    cam = get_object_or_404(Camera, pk=1)
    if request.method == 'POST':
        form = CameraForm(request.POST, instance=cam)
    else:
        form = CameraForm(instance=cam)
    return save_camera_form(request, form, 'dashboard/camera.html')

@login_required
def save_camera_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

tugas_akhir/dashboard/templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}
{% load static %}

{% block nav_bar_center %}

{% endblock %}

{% block nav_custom_menu %}
<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <ul class="nav navbar-nav">
        <a class="btn btn-primary" href="{% url 'logout' %}" role="button"> Logout <i class="nav-icon fas fa-door-open"></i> </a>
    </ul>
</ul>
{% endblock nav_custom_menu %}

tugas_akhir/dashboard/templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}
{% load adminlte_helpers %}
{% load static %}

{% block logo %}
<a href="{% url 'dashboard:index' %}" class="brand-link">
    <img src="{%static 'base/parkir.png' %}" alt="AdminLTE Logo" class="brand-image" style="opacity: .8">
    {% block logo_text %}<span class="brand-text font-weight-light">Smart Parkir </span>{% endblock %}
</a>
{% endblock %}

{% block user_panel %}
<div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="{% static 'base/user.jpg' size=100 %}" class="img-circle elevation-2" alt="User Image">
    </div>
    <div class="info">
        {% if user.is_authenticated %}
        <a href="{% url 'dashboard:index' %}" class="d-block">{{user.username}}</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block nav_heading %}
MENU UTAMA
{% endblock %}

{% block nav_links %}
<li class="nav-item">
    <a href="{% url 'dashboard:index' %}" class="nav-link {% add_active 'dashboard:index' exact_match=True %}">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>Dashboard</p>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'cekin:index' %}" class="nav-link {% add_active 'cekin:index' %}">
        <i class="nav-icon fas fa-archway"></i>
        <p>Gerbang Masuk</p>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'cekin_paraller:index' %}" class="nav-link {% add_active 'cekin_paraller:index' %}">
        <i class="nav-icon fas fa-archway"></i>
        <p>Gerbang Paraller</p>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'cekout:index' %}" class="nav-link {% add_active 'cekout:index' %}">
        <i class="nav-icon fas fa-archway"></i>
        <p>Gerbang Keluar</p>
    </a>
</li>
<li class="nav-item has-tree-view ">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-parking"></i>
        <p>Parkir</p>
        <p><i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview menu-open">
        <li class="nav-item">
            <a href="{% url 'parkir:titik' %}" class="nav-link {% add_active 'parkir:titik' %}">
                <i class="nav-icon fas fa-map-marker-alt"></i> Titik Parkir
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'parkir:cari_mobil' %}" class="nav-link {% add_active 'parkir:cari_mobil' %}">
                <i class="nav-icon fas fa-search-location"></i> Cari Mobil
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'parkir:parkir_kosong' %}" class="nav-link {% add_active 'parkir:parkir_kosong' %}">
                <i class="nav-icon fas fa-search"></i> Cari Tempat Kosong
            </a>
        </li>
    </ul>
</li>
<li class="nav-item">
    <a href="{% url 'mobil:index' %}" class="nav-link {% add_active 'mobil:index' %}">
        <i class="nav-icon fas fa-car-side"></i>
        <p>Data Mobil</p>
    </a>
</li>
{% endblock nav_links %}