tugas_akhir/cekin/urls.py
from django.urls import path

from . import views

app_name = 'cekin'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/',views.imgGerbang, name='image_gerbang'),
    path('tambah/',views.tambahImage, name='image_tambah'),
    path('deteksi/',views.deteksiImage, name='image_deteksi'),
    path('simpan/',views.simpanImage, name='image_simpan'),
    path('video/',views.videoGerbangMasuk, name='video_gerbang'),
    path('camera/', views.aturCamera, name='atur_camera'),
    path('set/', views.setImage, name='set_image'),
    path('<int:pk>/lihat/',views.lihatGambar, name='lihat_gambar'),
] 

tugas_akhir/parkir/urls.py
from django.urls import path

from . import views

app_name = 'parkir'
urlpatterns = [
    path('titik/', views.titik, name='titik'),
    path('titik/img/',views.imgTitik, name='image_titik'),
    path('titik/img/ganti/', views.editGambar, name='ganti_gambar'),
    path('titik/create/',views.createPosisi, name='create_posisi'),
    path('titik/<int:pk>/edit/', views.editPosisi, name='edit_posisi'),
    path('titik/<int:pk>/delete/', views.deletePosisi, name='delete_posisi'),
    path('cari_mobil/', views.cari_kendaraan_template, name='cari_mobil'), # template
    path('cari_kendaraan/', views.cari_kendaraan, name='cari_kendaraan'), # cari kendaraan
    path('parkir_kosong/',views.tempat_kosong_template, name='parkir_kosong'), # template
    path('img_tempat_kosong/', views.img_tempat_kosong, name='img_tempat_kosong'), # cari tempat kosong
] 

tugas_akhir/tugas_akhir/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('user_manage.urls')),
    path('home/', include('dashboard.urls')),
    path('gerbang/masuk/', include('cekin.urls')),
    path('gerbang/paraller/masuk/', include('cekin_paraller.urls')),
    path('gerbang/keluar/', include('cekout.urls')),
    path('mobil/', include('mobil.urls')),
    path('parkir/', include('parkir.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

tugas_akhir/parkir/models.py
from django.db import models

# Create your models here.

class Posisi(models.Model):
    nama = models.CharField(max_length=200)
    koordinat = models.CharField(max_length=200)
    koordinat_denah = models.CharField(max_length=200, default="")
    
class Parkir(models.Model):
    id_kendaraan = models.ForeignKey('mobil.Kendaraan',on_delete=models.CASCADE)
    id_posisi = models.ForeignKey(Posisi,on_delete=models.CASCADE)
    gambar_parkir = models.CharField(max_length=200 ,default="", editable=False)

tugas_akhir/parkir/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse ,JsonResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from .formTitik import PosisiForm
from .models import Posisi
from mobil.models import Kendaraan
from paket.reza import ImageProses
from json import dumps
import os
import base64
# Create your views here.

@login_required
def titik(request):
    posisi = Posisi.objects.all()
    return render(request, 'parkir/titik/titik.html', {'posisi':posisi})

@login_required
def imgTitik(request):
    image = ImageProses()
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__)) # File direktori
    image.setImage(PROJECT_ROOT+"/static/mobil/parkiran.jpg")
    image.setSize((400,300))
    posisi = Posisi.objects.all()
    img = image.get_imageTitikParkir(posisi)
    return HttpResponse(img)

@login_required
def editGambar(request):
    data = dict()
    image = ImageProses()
    template_name = 'parkir/titik/ganti_gambar.html'
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
    image.setImage(PROJECT_ROOT+"/static/mobil/parkiran.jpg")
    image.setDenah(PROJECT_ROOT+"/static/mobil/denah.png")
    image.setSize((400,300))
    parkiran = image.get_image()
    denah = image.get_denah()
    context = {'parkiran': parkiran, 'denah':denah}
    if request.method == 'POST':
        try:
            gambar_parkiran = request.POST.get("b64parkiran")
            gambar_denah = request.POST.get("b64denah")
            _, imgparkiran = gambar_parkiran.split(';base64,')
            _, imgdenah = gambar_denah.split(';base64,')
            with open(PROJECT_ROOT+"/static/mobil/parkiran.jpg", "wb") as fh:
                fh.write(base64.b64decode(imgparkiran))
            with open(PROJECT_ROOT+"/static/mobil/denah.png", "wb") as fh:
                fh.write(base64.b64decode(imgdenah))
            data['form_is_valid'] = True
            posisi = Posisi.objects.all()
            data['html_titik_list'] = render_to_string('parkir/titik/titik_list.html',{
                'posisi':posisi
            })
        except:
            data['form_is_valid'] = False
            data['html_form'] = render_to_string(template_name, context, request=request)
    else:
        data['form_is_valid'] = False
        data['html_form'] = render_to_string(template_name,context, request=request)
    return JsonResponse(data)

@login_required
def save_posisi_form(request, form, context, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            posisi = Posisi.objects.all()
            data['html_titik_list'] = render_to_string('parkir/titik/titik_list.html',{
                'posisi':posisi
            })
        else:
            data['form_is_valid'] = False
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@login_required
def createPosisi(request):
    if request.method == 'POST':
        form = PosisiForm(request.POST)
    else:
        form = PosisiForm()
    image = ImageProses()
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__)) # File direktori
    image.setImage(PROJECT_ROOT+"/static/mobil/parkiran.jpg")
    image.setDenah(PROJECT_ROOT+"/static/mobil/denah.png")
    image.setSize((400,300))
    parkiran = image.get_image()
    denah = image.get_denah()
    context = {'form': form, 'parkiran':parkiran, 'denah':denah}
    return save_posisi_form(request, form, context, 'parkir/titik/posisi_create.html')

@login_required
def editPosisi(request,pk):
    posisi = get_object_or_404(Posisi, pk=pk)
    if request.method == 'POST':
        form = PosisiForm(request.POST, instance=posisi)
    else:
        form = PosisiForm(instance=posisi)
    image = ImageProses()
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__)) # File direktori
    image.setImage(PROJECT_ROOT+"/static/mobil/parkiran.jpg")
    image.setDenah(PROJECT_ROOT+"/static/mobil/denah.png")
    image.setSize((400,300))
    parkiran = image.get_imageTitikParkirSebelum(posisi.koordinat, warna = (255,0,0))
    denah = image.get_denahTitikParkirSebelum(posisi.koordinat_denah, warna = (255,0,0))
    context = {'form': form, 'parkiran':parkiran, 'denah':denah}
    return save_posisi_form(request, form, context, 'parkir/titik/posisi_update.html')

@login_required
def deletePosisi(request, pk):
    posisi = get_object_or_404(Posisi, pk=pk)
    data = dict()
    if request.method == 'POST':
        posisi.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        posisi = Posisi.objects.all()
        data['html_titik_list'] = render_to_string('parkir/titik/titik_list.html',{
            'posisi':posisi
        })
    else:
        context = {'posisi': posisi}
        data['html_form'] = render_to_string('parkir/titik/posisi_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

@login_required
def cari_kendaraan_template(request):
    return render(request, 'parkir/cari_kendaraan/cari_mobil.html')

def cari_kendaraan(request):
    data = dict()
    image = ImageProses()
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__)) # File direktori
    image.setImage(PROJECT_ROOT+"/static/mobil/denah.png")
    image.setSize((400,300))
    if request.method == 'POST':
        plat = request.POST.get("plat")
        cek_mobil = Kendaraan.objects.filter(plat_nomor = plat,status_parkir=True,status_kendaraan=True)
        if len(cek_mobil) == 1:
            mobil = Posisi.objects.raw('SELECT * FROM parkir_posisi LEFT JOIN parkir_parkir ON parkir_posisi.id = parkir_parkir.id_posisi_id LEFT JOIN mobil_kendaraan ON parkir_parkir.id_kendaraan_id = mobil_kendaraan.id WHERE mobil_kendaraan.plat_nomor = "'+plat+'"')[0]
            img = image.get_imageCariKendaraan(mobil,(0,0,255))
            data['cek_in'] = mobil.cek_in
            data['cek_mobil'] = True
        else:
            img = image.get_image()
            data['cek_mobil'] = False
    else:
        img = image.get_image()
    data['img'] = img
    return JsonResponse(data)

@login_required
def tempat_kosong_template(request):
    return render(request, 'parkir/tempat_kosong/tempat_kosong.html')

def img_tempat_kosong(request):
    data = dict()
    image = ImageProses()
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__)) # File direktori
    image.setImage(PROJECT_ROOT+"/static/mobil/denah.png")
    image.setSize((400,300))
    data_parkir = Posisi.objects.raw('SELECT parkir_posisi.nama, parkir_posisi.koordinat_denah, parkir_parkir.id FROM parkir_posisi LEFT JOIN parkir_parkir ON parkir_posisi.id = parkir_parkir.id_posisi_id')    
    img, slot = image.get_imageParkirKosong(data_parkir)
    data['img'] = img
    data['slot'] = slot
    return JsonResponse(data)

tugas_akhir/parkir/templates/parkir/titik/ganti_gambar.html
{% load widget_tweaks %}

<form method="post" action="{% url 'parkir:ganti_gambar' %}" class="js-ganti-gambar-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Ganti gambar parkiran dan denah yang akan di olah</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="Awal">Gambar Parkiran</label> </br>
                    <img src="data:image/jpeg;base64, {{parkiran}}" alt="" id="displayParkiran" width="400" height="300"> 
                    <div class="mt-2">
                        <input type="file" name="img_awal" id="imageParkiran" onchange="encodeImgParkirantoBase64(this)">
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="Mobil">Gambar Denah</label> </br>
                    <img src="data:image/jpeg;base64, {{denah}}" alt="" id="displayDenah" width="400" height="300"> 
                    <div class="mt-2">
                        <input type="file" name="img_mobil" id="imageDenah" onchange="encodeImgDenahtoBase64(this)">
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" id="convertParkiran" name="b64parkiran">
        <input type="hidden" id="convertDenah" name="b64denah">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Ganti</button>
    </div>
</form>

tugas_akhir/parkir/templates/parkir/titik/posisi_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'parkir:create_posisi' %}" class="js-posisi-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Create Posisi Parkir</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="form-group{% if form.nama.errors %} has-error{% endif %}">
            <label for="{{ form.nama.id_for_label }}">{{ form.nama.label }}</label>
            {% render_field form.nama class="form-control" %}
            {% for error in form.nama.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group{% if form.koordinat.errors %} has-error{% endif %}">
                    <label for="{{ form.koordinat.id_for_label }}">{{ form.koordinat.label }}(x,y) = <b id="text-posisi"></b></label>
                    {% render_field form.koordinat class="form-control" id="form-posisi"%}
                    {% for error in form.koordinat.errors %}
                    <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <div class="col" style="width: 400px;">
                        <div id="image_preview">
                            <img src="data:image/jpeg;base64, {{parkiran}}" class="card-img-top">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group{% if form.koordinat_denah.errors %} has-error{% endif %}">
                    <label for="{{ form.koordinat_denah.id_for_label }}">{{ form.koordinat_denah.label }}(x,y) = <b id="text-posisi-denah"></b></label>
                    {% render_field form.koordinat_denah class="form-control" id="form-posisi-denah"%}
                    {% for error in form.koordinat_denah.errors %}
                    <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <div class="col" style="width: 400px;">
                        <div id="image_preview_denah">
                            <img src="data:image/jpeg;base64, {{denah}}" class="card-img-top">
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create Posisi</button>
    </div>
</form>

tugas_akhir/parkir/templates/parkir/titik/posisi_delete.html
<form method="post" action="{% url 'parkir:delete_posisi' posisi.id %}" class="js-posisi-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Konfirmasi penghapusan</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead">Apakah anda yakin menghapus titik parkir <strong>{{ posisi.nama }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete posisi</button>
    </div>
</form>

tugas_akhir/parkir/templates/parkir/titik/posisi_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'parkir:edit_posisi' form.instance.pk %}" class="js-posisi-update-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Update Posisi Parkir</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="form-group{% if form.nama.errors %} has-error{% endif %}">
            <label for="{{ form.nama.id_for_label }}">{{ form.nama.label }}</label>
            {% render_field form.nama class="form-control" %}
            {% for error in form.nama.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group{% if form.koordinat.errors %} has-error{% endif %}">
                    <label for="{{ form.koordinat.id_for_label }}">{{ form.koordinat.label }}(x,y) = <b id="text-posisi"></b></label>
                    {% render_field form.koordinat class="form-control" id="form-posisi"%}
                    {% for error in form.koordinat.errors %}
                    <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <div class="col" style="width: 400px;">
                        <div id="image_preview">
                            <img src="data:image/jpeg;base64, {{parkiran}}" class="card-img-top">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group{% if form.koordinat_denah.errors %} has-error{% endif %}">
                    <label for="{{ form.koordinat_denah.id_for_label }}">{{ form.koordinat_denah.label }}(x,y) = <b id="text-posisi-denah"></b></label>
                    {% render_field form.koordinat_denah class="form-control" id="form-posisi-denah"%}
                    {% for error in form.koordinat_denah.errors %}
                    <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <div class="col" style="width: 400px;">
                        <div id="image_preview_denah">
                            <img src="data:image/jpeg;base64, {{denah}}" class="card-img-top">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Update Posisi</button>
    </div>
</form>

tugas_akhir/parkir/templates/parkir/titik/titik.html
{% extends 'adminlte/base.html' %}
{% load static %}
{% block title %}Tugas akhir{% endblock %}

{% block extra_head %}
<style>
    #image_preview {
        position: relative;
        /* Add this since child are absolute! */
        background: #eee;
        cursor: crosshair;
    }

    #image_preview img {
        display: inline-block;
        vertical-align: top;
    }

    #image_preview_denah {
        position: relative;
        /* Add this since child are absolute! */
        background: #eee;
        cursor: crosshair;
    }

    #image_preview_denah img {
        display: inline-block;
        vertical-align: top;
    }

    .card-img-top {
        width: 400px;
        height: 300px;
        object-fit: cover;
    }

    .circle {
        position: absolute;
        border-radius: 50%;
        transform: translate(-50%, -50%);
        /* use translate instead of JS calculations */
    }

    .radius {
        position: absolute;
    }
</style>
{% endblock %}

{% block content_title %}
<h4><b>Titik Parkir</b></h4>
{% endblock %}
{% block content %}
<div class="row justify-content-md-center">
    <div class="col-5">
        <div class="card" style="width: 400px;">
            <div class="card-header">
                <b>Semua Titik Parkir</b>
            </div>
            <img id="img-titik" class="card-img-top" alt="parkir" data-url="{% url 'parkir:image_titik' %}">
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <button type="button" class="btn btn-primary btn-md btn-block js-ganti-gambar"
                            data-url="{% url 'parkir:ganti_gambar' %}">Ganti Gambar <i
                                class="nav-icon fas fa-folder"></i></button>
                    </div>
                    <div class="col-6">
                        <button type="button" class="btn btn-primary btn-md btn-block js-create-posisi"
                            data-url="{% url 'parkir:create_posisi' %}">Tambah Titik <i
                                class="nav-icon fas fa-folder-plus"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-7">
        <div class="card">
            <div class="card-header">
                <b>Daftar Titik Parkir</b>
            </div>
            <div class="card-body">
                <table id="example_titik" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width: 10%;">NO</th>
                            <th>Nama</th>
                            <th>Kordinat titik</th>
                            <th style="width: 30%;">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include 'parkir/titik/titik_list.html' %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-posisi">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-proses">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Proses Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
    function imgAjax() {
        $.ajax({
            url: $("#img-titik").attr('data-url'),
            type: 'GET',
            success: function (data) {
                $("#img-titik").attr("src", "data:image/jpeg;base64, " + data);
            }
        });
    }

    function table_data_titik() {
        $("#example_titik").DataTable({
            "lengthMenu": [[4, 8, 12, -1], [4, 8, 12, "All"]]
        });
    }


    function encodeImgParkirantoBase64(element) {

        var img = element.files[0];

        var reader = new FileReader();

        reader.onloadend = function () {

            $("#convertParkiran").val(reader.result);

            $("#displayParkiran").attr("src", reader.result);
        }
        reader.readAsDataURL(img);
    }

    function encodeImgDenahtoBase64(element) {

        var img = element.files[0];

        var reader = new FileReader();

        reader.onloadend = function () {

            $("#convertDenah").val(reader.result);

            $("#displayDenah").attr("src", reader.result);
        }
        reader.readAsDataURL(img);
    }

    var koordinat = "";
    var koordinat_denah = "";
    $(function () {
        table_data_titik();
        imgAjax();

        var loadForm = function () {
            var btn = $(this);
            $.ajax({
                url: btn.attr("data-url"),
                type: 'get',
                dataType: 'json',
                beforeSend: function () {
                    $("#modal-posisi").modal("show");
                },
                success: function (data) {
                    koordinat = data.parkiran
                    koordinat_denah = data.denah
                    $("#modal-posisi .modal-content").html(data.html_form);
                    $("#form-posisi").hide();
                    $("#form-posisi-denah").hide();
                }
            });
        };

        var saveForm = function () {
            var form = $(this);
            $.ajax({
                url: form.attr("action"),
                data: form.serialize(),
                type: form.attr("method"),
                dataType: 'json',
                success: function (data) {
                    if (data.form_is_valid) {
                        $("#modal-posisi").modal("hide");
                        $("#example_titik").DataTable().clear();
                        $("#example_titik").DataTable().destroy();
                        $("#example_titik tbody").html(data.html_titik_list);
                        table_data_titik();
                        imgAjax();
                    }
                    else {
                        $("#modal-posisi .modal-content").html(data.html_form);
                        $("#modal-proses").modal("show");
                        $("#modal-proses .modal-content .modal-body").html("<h5> Terdapat Kesalahan dalam pengisian form </h5>")
                    }
                }
            });
            return false;
        };

        // Ganti gambar
        $(".js-ganti-gambar").click(loadForm);
        $("#modal-posisi").on("submit", ".js-ganti-gambar-form", saveForm);

        // Create posisi
        $(".js-create-posisi").click(loadForm);
        $("#modal-posisi").on("submit", ".js-posisi-create-form", saveForm);

        // Update posisi
        $("#example_titik").on("click", ".js-update-posisi", loadForm);
        $("#modal-posisi").on("submit", ".js-posisi-update-form", saveForm);

        // Delete posisi
        $("#example_titik").on("click", ".js-delete-posisi", loadForm);
        $("#modal-posisi").on("submit", ".js-posisi-delete-form", saveForm);

        const $radius = 5;
        var titik = function (ev) {
            $('#image_preview').on('click', function (ev) {
                $("div").remove(".js-parkiran");
                const $this = $(this),
                    r = parseInt($radius, 10), // Parse as Integer radix 10
                    o = $this.offset(),
                    y = ev.pageY - o.top,
                    x = ev.pageX - o.left;

                $("<div />", {
                    "class": "circle js-parkiran",
                    "style": "background: rgba(255, 0, 0, 1) url(\"{% static 'base/dot.png' %}\") no-repeat 50% 50%",
                    css: {
                        top: y,
                        left: x,
                        width: r * 2,
                    },
                    height: r * 2,
                    appendTo: $this // append to #image_preview!
                });

                const $tx = Math.round(x)
                // Append data to App.points
                koordinat = $tx.toString() + ',' + y.toString()
                // App.points.push({ x, y, r });
                // Test
            });

            $('#image_preview_denah').on('click', function (ev) {
                $("div").remove(".js-denah");
                const $this = $(this),
                    r = parseInt($radius, 10), // Parse as Integer radix 10
                    o = $this.offset(),
                    y = ev.pageY - o.top,
                    x = ev.pageX - o.left;

                $("<div />", {
                    "class": "circle js-denah",
                    "style": "background: rgba(255, 0, 0, 1) url(\"{% static 'base/dot.png' %}\") no-repeat 50% 50%",
                    css: {
                        top: y,
                        left: x,
                        width: r * 2,
                    },
                    height: r * 2,
                    appendTo: $this // append to #image_preview!
                });

                const $tx = Math.round(x)
                // Append data to App.points
                koordinat_denah = $tx.toString() + ',' + y.toString()
                // App.points.push({ x, y, r });
                // Test
            });
            $('#text-posisi').text(koordinat)
            $('#form-posisi').val(koordinat)
            $('#text-posisi-denah').text(koordinat_denah)
            $('#form-posisi-denah').val(koordinat_denah)
        }
        $("#modal-posisi").click(titik);

    });


</script>
{% endblock %}

tugas_akhir/parkir/templates/parkir/titik/titik_list.html
{% for data in posisi %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ data.nama }}</td>
    <td>{{ data.koordinat }}</td>
    <td>
        <div class="row">
            <div class="col-4">
                <button type="button" class="btn btn-warning btn-sm js-update-posisi"
                    data-url="{% url 'parkir:edit_posisi' data.id %}">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </button>
            </div>
            <div class="col-8">
                <button type="button" class="btn btn-danger btn-sm js-delete-posisi"
                    data-url="{% url 'parkir:delete_posisi' data.id %}">
                    <span class="glyphicon glyphicon-trash"></span> Delete
                </button>
            </div>
        </div>
    </td>
</tr>
{% endfor %}