tugas_akhir/cekin/urls.py
from django.urls import path

from . import views

app_name = 'cekin'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/',views.imgGerbang, name='image_gerbang'),
    path('tambah/',views.tambahImage, name='image_tambah'),
    path('deteksi/',views.deteksiImage, name='image_deteksi'),
    path('simpan/',views.simpanImage, name='image_simpan'),
    path('video/',views.videoGerbangMasuk, name='video_gerbang'),
    path('camera/', views.aturCamera, name='atur_camera'),
    path('set/', views.setImage, name='set_image'),
    path('<int:pk>/lihat/',views.lihatGambar, name='lihat_gambar'),
] 

tugas_akhir/mobil/urls.py
from django.urls import path

from . import views

app_name = 'mobil'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create_kendaraan'),
    path('<int:pk>/edit/', views.edit, name='edit_kendaraan'),
    path('<int:pk>/delete/', views.delete, name='delete_kendaraan'),
    path('<int:pk>/lihat/', views.lihatParkir, name='lihat_parkir'),
] 

tugas_akhir/tugas_akhir/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('user_manage.urls')),
    path('home/', include('dashboard.urls')),
    path('gerbang/masuk/', include('cekin.urls')),
    path('gerbang/paraller/masuk/', include('cekin_paraller.urls')),
    path('gerbang/keluar/', include('cekout.urls')),
    path('mobil/', include('mobil.urls')),
    path('parkir/', include('parkir.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

tugas_akhir/mobil/models.py
from django.db import models

# Create your models here.
class Kendaraan(models.Model):
    plat_nomor = models.CharField(max_length=200)
    cek_in = models.CharField(max_length=200)
    cek_out = models.CharField(max_length=200)  
    status_kendaraan = models.BooleanField(default=True)
    status_parkir = models.BooleanField(default=False)
    gambar = models.CharField(max_length=200 ,default="", editable=False)  
    gambar_ori = models.CharField(max_length=200 ,default="", editable=False)  
    

tugas_akhir/mobil/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from .models import Kendaraan
from parkir.models import Parkir
from .formsMobil import KendaraanForm
from paket.reza import ImageProses
import os

# Create your views here.

@login_required
def index(request):
    kendaraan = Kendaraan.objects.raw('SELECT * FROM `mobil_kendaraan` LEFT JOIN parkir_parkir ON mobil_kendaraan.id = parkir_parkir.id_kendaraan_id LEFT JOIN parkir_posisi ON parkir_parkir.id_posisi_id = parkir_posisi.id')
    return render(request,'mobil/index.html',{'kendaraan':kendaraan})

@login_required
def save_kendaraan_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            kendaraan = Kendaraan.objects.raw('SELECT * FROM `mobil_kendaraan` LEFT JOIN parkir_parkir ON mobil_kendaraan.id = parkir_parkir.id_kendaraan_id LEFT JOIN parkir_posisi ON parkir_parkir.id_posisi_id = parkir_posisi.id')
            data['html_kendaraan_list'] = render_to_string('mobil/list.html', {
                'kendaraan': kendaraan
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@login_required
def create(request):
    if request.method == 'POST':
        form = KendaraanForm(request.POST)
    else:
        form = KendaraanForm()
    return save_kendaraan_form(request, form, 'mobil/create.html')

@login_required
def edit(request, pk):
    mobil = get_object_or_404(Kendaraan, pk=pk)
    if request.method == 'POST':
        form = KendaraanForm(request.POST, instance=mobil)
    else:
        form = KendaraanForm(instance=mobil)
    return save_kendaraan_form(request, form, 'mobil/edit.html')

@login_required
def delete(request, pk):
    mobil = get_object_or_404(Kendaraan, pk=pk)
    data = dict()
    if request.method == 'POST':
        os.remove(mobil.gambar)
        os.remove(mobil.gambar_ori)
        parkir = Parkir.objects.filter(id_kendaraan=mobil.id)
        if parkir: # jika mobil sudah terparkir
            os.remove(parkir[0].gambar_parkir)
        parkir.delete()
        mobil.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        kendaraan = Kendaraan.objects.raw('SELECT * FROM `mobil_kendaraan` LEFT JOIN parkir_parkir ON mobil_kendaraan.id = parkir_parkir.id_kendaraan_id LEFT JOIN parkir_posisi ON parkir_parkir.id_posisi_id = parkir_posisi.id')
        data['html_kendaraan_list'] = render_to_string('mobil/list.html', {
            'kendaraan': kendaraan
        })
    else:
        context = {'kendaraan': mobil}
        data['html_form'] = render_to_string('mobil/delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

@login_required
def lihatParkir(request,pk):
    data = dict()
    image = ImageProses()
    parkir = get_object_or_404(Parkir, id_kendaraan=pk)
    image.setImage(parkir.gambar_parkir)
    gambar_parkir = image.get_image()
    data['form_is_valid'] = True
    data['html_kendaraan_list'] = render_to_string('mobil/lihat_parkir.html', {
                'gambar_parkir': gambar_parkir
            })
    context = {'gambar_parkir':gambar_parkir}
    data['html_form'] = render_to_string('mobil/lihat_parkir.html', context, request=request)
    return JsonResponse(data)

tugas_akhir/mobil/templates/mobil/create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'mobil:create_kendaraan' %}" class="js-kendaraan-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Create Kendraan</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create Kendraan</button>
    </div>
</form>

tugas_akhir/mobil/templates/mobil/delete.html
<form method="post" action="{% url 'mobil:delete_kendaraan' kendaraan.id %}" class="js-kendaraan-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Konfirmasi penghapusan kendaraan</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead">Kamu yakin ingin menghapus kendaraan dengan plat nomor <strong>{{ kendaraan.plat_nomor }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete Kendaraan</button>
    </div>
</form>

tugas_akhir/mobil/templates/mobil/edit.html
{% load widget_tweaks %}

<form method="post" action="{% url 'mobil:edit_kendaraan' form.instance.pk %}" class="js-kendaraan-update-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Edit Kendraan</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Edit Kendraan</button>
    </div>
</form>

tugas_akhir/mobil/templates/mobil/index.html
{% extends 'adminlte/base.html' %}
{% load static %}
{% block title %}Tugas akhir{% endblock %}

{% block content_title %}
<h4><b>Data mobil</b></h4>
{% endblock %}
{% block content %}
<!-- <div class="row">
    <div class="col 12 mb-4">
        <button type="button" class="btn btn-primary js-create-kendaraan"
            data-url="{% url 'mobil:create_kendaraan' %}">Tambah Mobil <i
                class="nav-icon fas fa-folder-plus"></i></button>
    </div>
</div> -->
<div class="row">
    <div class="col 12">
        <table id="example_mobil" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th style="width: 3%;">NO</th>
                    <th>Plat Nomor</th>
                    <th>Waktu Cek-In</th>
                    <th>Waktu Cek-Out</th>
                    <th>Status Kendaraan</th>
                    <th>Status Parkir</th>
                    <th>Gambar Parkir</th>
                    <th style="width: 14%;">Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% include 'mobil/list.html' %}
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="modal-kendaraan">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script>
    function table_data_mobil() {
        $("#example_mobil").DataTable();
    }

    function dt_cek_in() {
        $('#id_cek_in').attr('autocomplete', 'off');
        $('#id_cek_in').inputmask("datetime",{
            mask: "1.2.y h:s",
            placeholder: "dd.mm.yyyy hh:mm",
            leapday: ".02.29",
            separator: ".",
            alias: "dd.mm.yyyy"
        });
        jQuery('#id_cek_in').datetimepicker({
            format: 'd.m.Y H:i',
            step: 1,
        });
    }

    function dt_cek_out() {
        $('#id_cek_out').attr('autocomplete', 'off');
        $('#id_cek_out').inputmask("datetime",{
            mask: "1.2.y h:s",
            placeholder: "dd.mm.yyyy hh:mm",
            leapday: ".02.29",
            separator: ".",
            alias: "dd.mm.yyyy"
        });
        jQuery('#id_cek_out').datetimepicker({
            format: 'd.m.Y H:i',
            step: 15,
        });
    }

    $(function () {
        table_data_mobil();

        var loadForm = function () {
            var btn = $(this);
            $.ajax({
                url: btn.attr("data-url"),
                type: 'get',
                dataType: 'json',
                beforeSend: function () {
                    $("#modal-kendaraan").modal("show");
                },
                success: function (data) {
                    $("#modal-kendaraan .modal-content").html(data.html_form);
                    dt_cek_in();
                    dt_cek_out();
                }
            });
        };

        var saveForm = function () {
            var form = $(this);
            $.ajax({
                url: form.attr("action"),
                data: form.serialize(),
                type: form.attr("method"),
                dataType: 'json',
                success: function (data) {
                    if (data.form_is_valid) {
                        $("#modal-kendaraan").modal("hide");
                        $("#example_mobil").DataTable().clear();
                        $("#example_mobil").DataTable().destroy();
                        $("#example_mobil tbody").html(data.html_kendaraan_list);
                        table_data_mobil();
                    }
                    else {
                        $("#modal-kendaraan .modal-content").html(data.html_form);
                        dt_cek_in();
                        dt_cek_out();
                    }
                }
            });
            return false;
        };


        /* Binding */

        // Create 
        $(".js-create-kendaraan").click(loadForm);
        $("#modal-kendaraan").on("submit", ".js-kendaraan-create-form", saveForm);

        // Update 
        $("#example_mobil").on("click", ".js-update-kendaraan", loadForm);
        $("#modal-kendaraan").on("submit", ".js-kendaraan-update-form", saveForm);

        // Delete 
        $("#example_mobil").on("click", ".js-delete-kendaraan", loadForm);
        $("#modal-kendaraan").on("submit", ".js-kendaraan-delete-form", saveForm);

        // Lihat parkir
        $("#example_mobil").on("click", ".js-lihat-parkir", loadForm);


    });
</script>

{% endblock %}

tugas_akhir/mobil/templates/mobil/lihat_parkir.html
{% load widget_tweaks %}
<div class="modal-header">
    <h4 class="modal-title">Gambar Posisi Parkir</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <img src="data:image/jpeg;base64, {{gambar_parkir}}" class="card-img-top">
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

tugas_akhir/mobil/templates/mobil/list.html
{% for mobil in kendaraan %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ mobil.plat_nomor }}</td>
    <td>{{ mobil.cek_in }}</td>

    {% if mobil.cek_out == "" %}
    <td>Belum Keluar</td>
    {% else %}
    <td>{{ mobil.cek_out }}</td>
    {% endif %}

    {% if mobil.status_kendaraan == True %}
    <td>Masuk</td>
    {% else %}
    <td>Keluar</td>
    {% endif %}

    {% if mobil.nama == None %}
    <td>Belum Terparkir</td>
    {% else %}
    <td>{{ mobil.nama }}</td>
    {% endif %}

    {% if mobil.nama == None %}
    <td>Belum Terparkir</td>
    {% else %}
    <td>
        <button type="button" class="btn btn-success btn-sm js-lihat-parkir"
            data-url="{% url 'mobil:lihat_parkir' mobil.id %}">
            <span class="glyphicon glyphicon-pencil"></span> Lihat
        </button>
    </td>
    {% endif %}
    <td>
        <button type="button" class="btn btn-warning btn-sm js-update-kendaraan"
            data-url="{% url 'mobil:edit_kendaraan' mobil.id %}">
            <span class="glyphicon glyphicon-pencil"></span> Edit
        </button>
        <button type="button" class="btn btn-danger btn-sm js-delete-kendaraan"
            data-url="{% url 'mobil:delete_kendaraan' mobil.id %}">
            <span class="glyphicon glyphicon-trash"></span> Delete
        </button>
    </td>
</tr>
{% endfor %}