tugas_akhir/cekin/urls.py
from django.urls import path

from . import views

app_name = 'cekin'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/',views.imgGerbang, name='image_gerbang'),
    path('tambah/',views.tambahImage, name='image_tambah'),
    path('deteksi/',views.deteksiImage, name='image_deteksi'),
    path('simpan/',views.simpanImage, name='image_simpan'),
    path('video/',views.videoGerbangMasuk, name='video_gerbang'),
    path('camera/', views.aturCamera, name='atur_camera'),
    path('set/', views.setImage, name='set_image'),
    path('<int:pk>/lihat/',views.lihatGambar, name='lihat_gambar'),
] 

tugas_akhir/cekin_paraller/urls.py
from django.urls import path

from . import views

app_name = 'cekin_paraller'
urlpatterns = [
    path('', views.index, name='index'),
    path('img/',views.imgGerbang, name='image_gerbang'),
    path('tambah/',views.tambahImage, name='image_tambah'),
    path('deteksi/',views.deteksiImage, name='image_deteksi'),
    path('simpan/',views.simpanImage, name='image_simpan'),
    path('<int:pk>/lihat/',views.lihatGambar, name='lihat_gambar'),
] 

tugas_akhir/tugas_akhir/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('user_manage.urls')),
    path('home/', include('dashboard.urls')),
    path('gerbang/masuk/', include('cekin.urls')),
    path('gerbang/paraller/masuk/', include('cekin_paraller.urls')),
    path('gerbang/keluar/', include('cekout.urls')),
    path('mobil/', include('mobil.urls')),
    path('parkir/', include('parkir.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

tugas_akhir/cekin_paraller/models.py
from django.db import models

# Create your models here.

tugas_akhir/cekin_paraller/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.template.loader import render_to_string
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required

from mobil.models import Kendaraan
from paket.reza import ImageProses
from datetime import datetime
import os
import base64

# Create your views here.
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

@login_required
def index(request):
    kendaraan = Kendaraan.objects.all().order_by('-id')
    return render(request, 'cekin_paraller/index.html',{'kendaraan':kendaraan})

@login_required
def imgGerbang(request):
    global PROJECT_ROOT
    data = dict()
    image = ImageProses()
    if request.method == 'POST':
        try:
            gambar_awal = request.POST.get("b64awal")
            gambar_mobil = request.POST.get("b64mobil")
            gambar_mobil_paraller = request.POST.get("b64mobilParaller")
            _, imgawal = gambar_awal.split(';base64,')
            _, imgmobil = gambar_mobil.split(';base64,')
            _, imgmobil_paraller = gambar_mobil_paraller.split(';base64,')
            with open(PROJECT_ROOT+"/static/imageParaller/imageAwal.jpg", "wb") as fh:
                fh.write(base64.b64decode(imgawal))
            with open(PROJECT_ROOT+"/static/imageParaller/imageMobil.jpg", "wb") as fh:
                fh.write(base64.b64decode(imgmobil))
            with open(PROJECT_ROOT+"/static/imageParaller/imageMobilParaller.jpg", "wb") as fh:
                fh.write(base64.b64decode(imgmobil_paraller))
            image.setImage(PROJECT_ROOT+"/static/imageParaller/imageMobilParaller.jpg")
            data['form_is_valid'] = True
        except:
            data['html_form'] = render_to_string('cekin_paraller/tambah_gambar.html', request=request)
            data['form_is_valid'] = False
    else:
        data['form_is_valid'] = False
    image.setSize((500,500))
    img = image.get_image()
    data['img'] = img
    return JsonResponse(data)

@login_required
def deteksiImage(request):
    global PROJECT_ROOT
    data = dict()
    image = ImageProses()
    x = int(request.POST.get("x"))
    y = int(request.POST.get("y"))
    w = int(request.POST.get("width"))
    h = int(request.POST.get("height"))
    image.setImage(PROJECT_ROOT+"/static/imageParaller/imageMobilParaller.jpg") 
    image.setSize((500,500))
    text = image.get_ocrPlat(x,y,w,h)
    data['text'] = text
    return JsonResponse(data)

@login_required
def simpanImage(request):
    global PROJECT_ROOT
    data = dict()
    imgawal = PROJECT_ROOT+"/static/imageParaller/imageAwal.jpg"
    image = ImageProses()
    image.setImage(PROJECT_ROOT+"/static/imageParaller/imageMobil.jpg") 
    mobil_asli = PROJECT_ROOT+"/static/imageParaller/imageMobilParaller.jpg"
    image.setSize((768,432))
    text = request.POST.get("text")
    cek_mobil = Kendaraan.objects.filter(plat_nomor = text)
    if len(cek_mobil)==0:
        data['text'] = text
        today = datetime.today()
        date = today.strftime("%d.%m.%Y %H:%M")
        img_ori ,img_dir = image.get_sift_paraller(imgawal,mobil_asli)
        mobil = Kendaraan(plat_nomor = text,cek_in = date,status_kendaraan = True,status_parkir = False,gambar=img_dir,gambar_ori = img_ori)
        mobil.save()
        data['cek_mobil'] = True
    else:
        data['cek_mobil'] = False        
    kendaraan = Kendaraan.objects.all().order_by('-id')
    data['html_list'] = render_to_string('cekin_paraller/list.html',{
        'kendaraan':kendaraan
    })        
    return JsonResponse(data)

@login_required
def lihatGambar(request,pk):
    data = dict()
    image = ImageProses()
    mobil = get_object_or_404(Kendaraan, pk=pk)
    image.setImage(mobil.gambar_ori)
    gambar_mobil = image.get_image()
    data['form_is_valid'] = True
    data['html_kendaraan_list'] = render_to_string('cekin_paraller/lihat_gambar.html', {
                'gambar_mobil': gambar_mobil
            })
    context = {'gambar_mobil':gambar_mobil}
    data['html_form'] = render_to_string('cekin_paraller/lihat_gambar.html', context, request=request)
    return JsonResponse(data)

# hanya template form
@login_required
def tambahImage(request): 
    data = dict()
    template_name = 'cekin_paraller/tambah_gambar.html'
    data['html_form'] = render_to_string(template_name, request=request)
    return JsonResponse(data)

tugas_akhir/cekin_paraller/templates/cekin_paraller/index.html
{% extends 'adminlte/base.html' %}
{% load static %}
{% block title %}Tugas akhir{% endblock %}

{% block extra_head %}
<style>
    .frame_gerbang_paraller {
        background: #cacaca;
        width: 500px;
        height: 500px;
        border: 1px solid black;
    }

    .selectiondiv {
        border: 2px solid white;
        background: rgb(224, 20, 47);
        opacity: 0.4;
        filter: alpha(opacity=40);
        margin: 0px;
        padding: 0px;
        display: none;
    }
</style>
{% endblock %}

{% block content_title %}
<h4><b>Cek-In Kendaraan</b></h4>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-7">
        <div class="card text-center">
            <div class="card-header">
                <b>Gambar Kendaraan</b>
            </div>
            <div class="card-body">
                <div class="row">
                    <div onmousedown="return false" id="YDR-Frame" class="frame_gerbang_paraller"
                        data-url="{% url 'cekin_paraller:image_gerbang' %}">
                        <div id="selection" class="selectiondiv"></div>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6">
                                <button type="button" class="btn btn-primary btn-md btn-block js-create-gerbang"
                                    data-url="{% url 'cekin_paraller:image_tambah' %}" data-toggle="modal"
                                    data-target="#exampleModal">
                                    Tambah Gambar
                                </button>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn btn-primary btn-md btn-block js-create-deteksi"
                                    data-url="{% url 'cekin_paraller:image_deteksi' %}" data-toggle="modal"
                                    data-target="#exampleModal">
                                    Deteksi
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" id="ocr_text" placeholder="Hasil Deteksi"
                                aria-label="Recipient's username" aria-describedby="button-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-primary" id="simpan_data" type="button"
                                    data-url="{% url 'cekin_paraller:image_simpan' %}">Simpan</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <b>Daftar Mobil Masuk</b>
            </div>
            <div class="card-body">
                <table id="example_gerbang" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width: 10%;">NO</th>
                            <th>Plat Nomor</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include 'cekin_paraller/list.html' %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-gerbang">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

<div class="modal fade" id="modal-proses">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Proses menyimpan data mobil</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4> Proses sedang berjalan mohon tunggu </h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script>
    $.ajax({
        url: $("#YDR-Frame").attr('data-url'),
        type: 'GET',
        success: function (data) {
            if (data.form_is_valid == false) {
                $('.js-create-deteksi').prop('disabled', true);
                $('#ocr_text').prop('disabled', true);
                $('#simpan_data').prop('disabled', true);
            }
            $(".frame_gerbang_paraller").css("background-image", "url(data:image/jpeg;base64," + data.img + ")");
        }
    });

    // Click coordinates
    var x1, x2, y1, y2, WIDTH, HEIGHT;

    function table_data_gerbang() {
        $("#example_gerbang").DataTable({
            "lengthMenu": [[7, 14, 21, -1], [7, 14, 21, "All"]],
            "searching": false,
            "bInfo": false,
        });
    }
    table_data_gerbang();

    // Variable indicates wether a mousedown event within your selection happend or not
    var selection = false;

    // Global mouse button variables
    var gMOUSEUP = false;
    var gMOUSEDOWN = false;

    // Global Events if left mousebutton is pressed or nor (usability fix)
    $(document).mouseup(function () {
        gMOUSEUP = true;
        gMOUSEDOWN = false;
    });
    $(document).mousedown(function () {
        gMOUSEUP = false;
        gMOUSEDOWN = true;
    });

    // Selection frame (playground :D)
    $("#YDR-Frame").mousedown(function (e) {
        selection = true;
        // store mouseX and mouseY
        x1 = e.pageX - $(this).offset().left;
        y1 = e.pageY - $(this).offset().top;
    });

    // If selection is true (mousedown on selection frame) the mousemove 
    // event will draw the selection div
    $('#YDR-Frame').mousemove(function (e) {
        if (selection) {
            // Store current mouseposition
            x2 = e.pageX - $(this).offset().left;
            y2 = e.pageY - $(this).offset().top;

            // Prevent the selection div to get outside of your frame
            (x2 < 0) ? selection = false : ($(this).width() < x2) ? selection = false : (y2 < 0) ? selection = false : ($(this).height() < y2) ? selection = false : selection = true;;

            // If the mouse is inside your frame resize the selection div
            if (selection) {
                // Calculate the div selection rectancle for positive and negative values
                var TOP = (y1 < y2) ? y1 : y2;
                var LEFT = (x1 < x2) ? x1 : x2;
                WIDTH = (x1 < x2) ? x2 - x1 : x1 - x2;
                HEIGHT = (y1 < y2) ? y2 - y1 : y1 - y2;

                // Use CSS to place your selection div
                $("#selection").css({
                    position: 'relative',
                    zIndex: 5000,
                    left: LEFT,
                    top: TOP,
                    width: WIDTH,
                    height: HEIGHT
                });
                $("#selection").show();

                // Info output
                $('#status2').html('( X : ' + x1 + ' )  ( Y : ' + y1 + ' )  ( width : ' + WIDTH + ' )  ( height : ' + HEIGHT + ' ) ');
            }
        }
    });
    // Selection complete, hide the selection div (or fade it out)
    $('#YDR-Frame').mouseup(function () {
        selection = false;
        // $("#selection").hide();
    });
    // Usability fix. If mouse leaves the selection and enters the selection frame again with mousedown
    $("#YDR-Frame").mouseenter(function () {
        (gMOUSEDOWN) ? selection = true : selection = false;
    });
    // Usability fix. If mouse leaves the selection and enters the selection div again with mousedown
    $("#selection").mouseenter(function () {
        (gMOUSEDOWN) ? selection = true : selection = false;
    });
    // Set selection to false, to prevent further selection outside of your selection frame
    $('#YDR-Frame').mouseleave(function () {
        selection = false;
    });

    function encodeImgAwaltoBase64(element) {

        var img = element.files[0];

        var reader = new FileReader();

        reader.onloadend = function () {

            $("#convertAwal").val(reader.result);

            $("#displayImgAwal").attr("src", reader.result);
        }
        reader.readAsDataURL(img);
    }

    function encodeImgMobiltoBase64(element) {

        var img = element.files[0];

        var reader = new FileReader();

        reader.onloadend = function () {

            $("#convertMobil").val(reader.result);

            $("#displayImgMobil").attr("src", reader.result);
        }
        reader.readAsDataURL(img);
    }

    function encodeImgMobilParallertoBase64(element) {

        var img = element.files[0];

        var reader = new FileReader();

        reader.onloadend = function () {

            $("#convertMobilParaller").val(reader.result);

            $("#displayImgMobilParaller").attr("src", reader.result);
        }
        reader.readAsDataURL(img);
    }

    var loadForm = function () {
        var btn = $(this);
        $.ajax({
            url: btn.attr("data-url"),
            type: 'get',
            dataType: 'json',
            beforeSend: function () {
                $("#modal-gerbang").modal("show");
            },
            success: function (data) {
                $("#modal-gerbang .modal-content").html(data.html_form);
            }
        });
    };

    var saveForm = function () {
        var form = $(this);
        $.ajax({
            url: form.attr("action"),
            data: form.serialize(),
            type: form.attr("method"),
            dataType: 'json',
            success: function (data) {
                if (data.form_is_valid) {
                    $("#modal-gerbang").modal("hide");
                    $(".frame_gerbang_paraller").css("background-image", "url(data:image/jpeg;base64," + data.img + ")");
                    $('.js-create-deteksi').prop('disabled', false);
                }
                else {
                    $("#modal-gerbang .modal-content").html(data.html_form);
                    $("#modal-proses").modal("show");
                    $("#modal-proses .modal-content .modal-body").html('<h4> Terdapat kesalahan pada pengisian form </h4>')
                }
            }
        });
        return false;
    };

    // menambah gambar yang akan di olah
    $(".js-create-gerbang").click(loadForm);
    $("#modal-gerbang").on("submit", ".js-gerbang-create-form", saveForm);

    // lihat gambar
    $("#example_gerbang").on("click", ".js-lihat-mobil", loadForm);

    var csrftoken = '{{csrf_token}}';
    $(".js-create-deteksi").on('click', function () {
        var btn = $(this);
        if (x1 == null & y1 == null & WIDTH == null & HEIGHT == null) {
            $("#modal-proses").modal("show");
            $("#modal-proses .modal-content .modal-body").html('<h4> Data area seleksi tidak boleh kosong </h4>')
        } else {
            var titik = {
                x: x1,
                y: y1,
                width: WIDTH,
                height: HEIGHT
            }
            $.ajax({
                url: btn.attr("data-url"),
                data: titik,
                type: 'post',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                success: function (data) {
                    $("#ocr_text").val(data.text);
                    $('#ocr_text').prop('disabled', false);
                    $('#simpan_data').prop('disabled', false);
                }
            });
        }
    });

    $("#simpan_data").on('click', function () {
        var btn = $(this);
        var ocr = $("#ocr_text").val()
        if (ocr === "") {
            $("#modal-proses").modal("show");
            $("#modal-proses .modal-content .modal-body").html('<h4> Hasil mengenalan tidak ada, harap lakukan seleksi area lagi !!! </h4>')
        } else {
            var data_text = { text: ocr }
            $.ajax({
                url: btn.attr("data-url"),
                data: data_text,
                type: 'post',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                beforeSend: function () {
                    $("#modal-proses").modal("show");
                },
                success: function (data) {
                    if (data.cek_mobil == false) {
                        $("#modal-proses .modal-content .modal-body").html('<h4> Kendaraan dengan plat nomor tersebut sudah ada </h4>')
                    } else {
                        $("#example_gerbang").DataTable().clear();
                        $("#example_gerbang").DataTable().destroy();
                        $("#example_gerbang tbody").html(data.html_list);
                        table_data_gerbang();
                        $("#modal-proses").modal("hide");
                    }
                }
            });
        }
    });

</script>
{% endblock %}

tugas_akhir/cekin_paraller/templates/cekin_paraller/lihat_gambar.html
{% load widget_tweaks %}
<div class="modal-header">
    <h4 class="modal-title">Gambar Mobil</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <img src="data:image/jpeg;base64, {{gambar_mobil}}" class="card-img-top">
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

tugas_akhir/cekin_paraller/templates/cekin_paraller/list.html
{% for data in kendaraan %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ data.plat_nomor }}</td>
    <td>
        <button type="button" class="btn btn-success btn-sm js-lihat-mobil"
            data-url="{% url 'cekin_paraller:lihat_gambar' data.id %}">
            <span class="glyphicon glyphicon-pencil"></span> Lihat
        </button>
    </td>
</tr>
{% endfor %}

tugas_akhir/cekin_paraller/templates/cekin_paraller/tambah_gambar.html
{% load widget_tweaks %}

<form method="post" action="{% url 'cekin_paraller:image_gerbang' %}" class="js-gerbang-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Tambah gambar yang akan di olah</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="Awal">Pilih gambar awal</label> </br>
                    <img src="" alt="" id="displayImgAwal" width="100" height="100"> 
                    <div class="mt-2">
                        <input type="file" name="img_awal" id="img_awal" onchange="encodeImgAwaltoBase64(this)">
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="Mobil">Pilih gambar mobil</label> </br>
                    <img src="" alt="" id="displayImgMobil" width="100" height="100"> 
                    <div class="mt-2">
                        <input type="file" name="img_mobil" id="img_mobil" onchange="encodeImgMobiltoBase64(this)">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="MobilParaller">Pilih gambar mobil Paraller</label> </br>
            <img src="" alt="" id="displayImgMobilParaller" width="100" height="100"> 
            <div class="mt-2">
                <input type="file" name="img_mobil_paraller" id="img_mobil_paraller" onchange="encodeImgMobilParallertoBase64(this)">
            </div>
        </div>
        <input type="hidden" id="convertMobil" name="b64mobil">
        <input type="hidden" id="convertMobilParaller" name="b64mobilParaller">
        <input type="hidden" id="convertAwal" name="b64awal">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Tambah</button>
    </div>
</form>